export const SUPABASE_URL = "https://dptapivncwuffdevptrq.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwdGFwaXZuY3d1ZmZkZXZwdHJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODMyMjM1MDgsImV4cCI6MjA5ODc5OTUwOH0.e7weFdHRDQEz31L-CkMVBf9bCK69R_Yek4Yl7yLGBVA";
